## 1.4 Combining Data from Multiple Tables


In [ ]:
import pandas as pd

## Introduction

Welcome to the "Combining Data from Multiple Tables" lesson! I am excited to introduce you to this topic, which will allow you to work with data from multiple sources to enhance your storytelling capabilities and uncover valuable insights. By practicing some key concepts in combining tables, you will form a valuable basis of understanding in combining tables. In this Jupyter notebook, we will explore how to merge data from multiple tables using the pandas library in Python.

## What does it mean to combine tables, and why would we want to do it?
We now define what it means to combine tables and provide motivation for doing so. First, consider what a table is. The following is an example of a table:

In [ ]:
# Larger product table
product_data = {
    'Product ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Product Name': ['Laptop', 'Smartphone', 'Tablet', 'Smartwatch', 'Laptop', 'Smartphone', 'Tablet', 'Smartwatch'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics'],
    'Brand': ['Brand A', 'Brand A', 'Brand A', 'Brand A', 'Brand B', 'Brand B', 'Brand B', 'Brand B']
}

product_df = pd.DataFrame(product_data)
print("Product Table:")
display(product_df)

Product Table:


Product ID Product Name     Category    Brand
0         101       Laptop  Electronics  Brand A
1         102   Smartphone  Electronics  Brand A
2         103       Tablet  Electronics  Brand A
3         104   Smartwatch  Electronics  Brand A
4         105       Laptop  Electronics  Brand B
5         106   Smartphone  Electronics  Brand B
6         107       Tablet  Electronics  Brand B
7         108   Smartwatch  Electronics  Brand B

Generally speaking, in a table, each row provides information about a separate entity. In the table above, the entities are products. Each column contains a different attribute of the entity. In the example above, those attributes are Product ID, Product Name, and Category. A Pandas DataFrame also contains an index for each row, which you can see on the left side of the table.

We *combine tables* when we integrate the information in one table with the information in another to obtain a larger dataset or a dataset with a larger capacity for insights. Suppose we had another table with the following information:


In [ ]:
# Separate table with product ID and cost
cost_data = {
    'Product ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Cost': [800, 500, 300, 250, 850, 550, 350, 275]
}

cost_df = pd.DataFrame(cost_data)
print("\nCost Table:")
display(cost_df)


Cost Table:


Product ID  Cost
0         101   800
1         102   500
2         103   300
3         104   250
4         105   850
5         106   550
6         107   350
7         108   275

Alone, the first table does not provide much opportunity for insight. It allows us to create a histogram of product types and a sense of which brands offers which products, but little else. By combining the first table with the second table, we can unlock deeper insights. What are some additional forms of analysis we could do by combining the first and second tables?
*   Determine the average cost of each product. E.g. the average cost of a smartphone.
*   Determine the % difference in cost between the average Brand A smartphone and the average Brand B smartphone.




## Core Technical Tools

Depending on what kind of programming language you are using, there are different technical tools for storing tables and combining them. In this lesson, we store data in pandas DataFrames, and we use the pandas merge function to combine them.

Below, we use the pd.merge function to merge the DataFrames above:

In [ ]:
pd.merge(product_df, cost_df, on='Product ID')

Product ID Product Name     Category    Brand  Cost
0         101       Laptop  Electronics  Brand A   800
1         102   Smartphone  Electronics  Brand A   500
2         103       Tablet  Electronics  Brand A   300
3         104   Smartwatch  Electronics  Brand A   250
4         105       Laptop  Electronics  Brand B   850
5         106   Smartphone  Electronics  Brand B   550
6         107       Tablet  Electronics  Brand B   350
7         108   Smartwatch  Electronics  Brand B   275

Before merging tables, we can first carefully envision what kind of table we want to produce. By understanding the information that you want to capture in the resulting table, you can better understand how to 

When we perform a merge operation, we use a certain column as a basis for merging. In the above example, we used Product ID. Notice that both tables had all the same product IDs available—both had 101 through 108. Suppose that one table had only 101 through 106. What would we do then? This is why we need to consider the 'how' parameter of the merge function. In the examples below, we illustrate how different kinds of joins can allow us to work with situations where we have missing data in a DataFrame.

Imagine that we have a dataset of all of the cities that have been affected by a recent disease outbreak. We have a dataset that contains a list of those cities and their city IDs. Suppose we also have a dataset with populations correspondign to several city IDs, but the population DataFrame does not include all of the city IDs that have been affected by the outbreak. Now suppose we want to create a table with each city and its population for a publication. We want to make sure that each city that has been affected by the outbreak is included in the table. We accomplish this as follows:

In [ ]:
iranian_cities = pd.DataFrame({'city_id': [1, 2, 3], 'city_name': ['Tehran', 'Mashhad', 'Isfahan']})
city_populations = pd.DataFrame({'city_id': [1, 2], 'population': [9172195, 3203253]})

merged = pd.merge(left = iranian_cities, right = city_populations, on='city_id', how='left')
merged

city_id city_name  population
0        1    Tehran   9172195.0
1        2   Mashhad   3203253.0
2        3   Isfahan         NaN

The merge() function will take all the rows from the left DataFrame (iranian_cities) and attempt to match them with the corresponding rows in the right DataFrame (city_populations) based on the city_id column. If a matching row is found in the right DataFrame, then the corresponding information from the right DataFrame is included in the resulting DataFrame. If no matching row is found, then the values in the right DataFrame will be filled with NaN.

Therefore, by specifying how='left', we ensure that all the cities in iranian_cities DataFrame are present in the resulting DataFrame, regardless of whether or not there is a corresponding row in the city_populations DataFrame. If we had specified how='right', then all the cities in city_populations DataFrame would have been included in the resulting DataFrame, and any cities in iranian_cities without a corresponding row in city_populations would have been excluded, as we see below:

In [ ]:
right_merged = pd.merge(iranian_cities, city_populations, on='city_id', how='right')
right_merged

city_id city_name  population
0        1    Tehran     9172195
1        2   Mashhad     3203253

In the above, we used a left merge and contrasted it with a right merge. To illustrate other types of merges, we go through further examples.

Suppose that we want to create a table with the nutritional content of our friends' favorite fruits. We have a table with our friends, and we have a table with the nutritional content of certain fruits. What happens when we use inner merge vs. outer merge to merge these two tables?

In [ ]:
# Create the first dataset with information about people and their favorite fruits
people_fruits_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Edward"],
    "Favorite_Fruit": ["Apple", "Banana", "Grapes", "Orange","Papaya"]
}

people_fruits_df = pd.DataFrame(people_fruits_data)

# Create the second dataset with the nutritional content of various fruits
nutritional_content_data = {
    "Fruit": ["Apple", "Banana", "Grapes", "Orange", "Pineapple"],
    "Calories": [95, 89, 67, 47, 50],
    "Vitamin_C_mg": [4.6, 8.7, 3.2, 45, 48],
    "Fiber_g": [2.4, 2.6, 0.9, 2.4, 1.4]
}

nutritional_content_df = pd.DataFrame(nutritional_content_data)

We now merge the two DataFrames using an inner merge.

In [ ]:
# Merge the datasets using an inner merge
merged_data = pd.merge(
    people_fruits_df, nutritional_content_df,
    left_on="Favorite_Fruit", right_on="Fruit",
    how="inner"
)

# Drop the 'Fruit' column since it's redundant
merged_data = merged_data.drop(columns="Fruit")

# Display the merged dataset
display(merged_data)

Name Favorite_Fruit  Calories  Vitamin_C_mg  Fiber_g
0    Alice          Apple        95           4.6      2.4
1      Bob         Banana        89           8.7      2.6
2  Charlie         Grapes        67           3.2      0.9
3    David         Orange        47          45.0      2.4

Now, observe what happens when we use an outer merge.

In [ ]:
# Merge the datasets using an inner merge
merged_data = pd.merge(
    people_fruits_df, nutritional_content_df,
    left_on="Favorite_Fruit", right_on="Fruit",
    how="outer"
)

# Drop the 'Fruit' column since it's redundant
merged_data = merged_data.drop(columns="Fruit")

# Display the merged dataset
display(merged_data)

Name Favorite_Fruit  Calories  Vitamin_C_mg  Fiber_g
0    Alice          Apple      95.0           4.6      2.4
1      Bob         Banana      89.0           8.7      2.6
2  Charlie         Grapes      67.0           3.2      0.9
3    David         Orange      47.0          45.0      2.4
4   Edward         Papaya       NaN           NaN      NaN
5      NaN            NaN      50.0          48.0      1.4

An inner merge (or inner join) between two dataframes returns only the matching rows between the two dataframes, based on the specified common columns. In other words, only the rows with matching values in both dataframes are included in the merged dataframe.

An outer merge (or outer join) returns all the rows from both dataframes and fills in missing values with NaN (or a specified fill value) for any non-matching rows. In other words, it includes all the rows from both dataframes and merges the common rows based on the specified common columns.

To more deeply understand merges, you can modify the "how" parameter in the above to change the merge type to "left" or "right." Then, you can observe how the merged DataFrame changes.

#### Finding the appropriate merge type

The type of analysis we do can determine the type of merge that is appropriate. In the following example, imagine that we are trying to analyze the locations of customers that have purchased different kinds of product product.

In this case, using a right merge makes sense because our primary focus is on the product sales data, and we want to include all sales records in the final dataset. The right merge ensures that all product sales records are included, regardless of whether there is a matching customer in the customer information dataset.

If we were to use a left merge or an inner merge, it would exclude any product sales records that do not have a corresponding customer in the customer information dataset, which may not be desirable if we want a complete overview of product sales.

In [ ]:
# Create the first dataset with customer information
customer_information_data = {
    "ID": [1, 2, 3, 4],
    "Name": ["John Doe", "Jane Smith", "Michael Brown", "Lucy Green"],
    "Email": ["john.doe@example.com", "jane.smith@example.com", "michael.brown@example.com", "lucy.green@example.com"],
    "Location": ["New York, NY","New York, NY","Chester, NJ","Boston, MA"]
}

customer_information_df = pd.DataFrame(customer_information_data)

# Create the second dataset with product sales information
product_sales_data = {
    "Product_ID": [101, 102, 103, 104, 105],
    "Product_Name": ["Laptop", "Monitor", "Keyboard", "Mouse", "Headset"],
    "Units_Sold": [50, 120, 200, 180, 80],
    "Customer_ID": [1, 2, 3, 1, 3]
}

product_sales_df = pd.DataFrame(product_sales_data)


In [ ]:
# Merge the datasets
merged_data = pd.merge(customer_information_df,
    product_sales_df,
    left_on="ID", right_on="Customer_ID",
    how="right"
)
display(merged_data)

ID           Name                      Email      Location  Product_ID  \
0   1       John Doe       john.doe@example.com  New York, NY         101   
1   2     Jane Smith     jane.smith@example.com  New York, NY         102   
2   3  Michael Brown  michael.brown@example.com   Chester, NJ         103   
3   1       John Doe       john.doe@example.com  New York, NY         104   
4   3  Michael Brown  michael.brown@example.com   Chester, NJ         105   

  Product_Name  Units_Sold  Customer_ID  
0       Laptop          50            1  
1      Monitor         120            2  
2     Keyboard         200            3  
3        Mouse         180            1  
4      Headset          80            3

We have two small datasets, one with sales data for different products in various regions, and the other with regional tax rates. We use a right merge to include all regions with tax rate information in the resulting dataset, even if there is no matching product sales data.

In [ ]:
# Sales data
sales_data = {
    'region': ['North', 'South', 'East', 'West'],
    'product': ['A', 'B', 'C', 'D'],
    'sales': [1000, 1200, 900, 1100],
}

sales_df = pd.DataFrame(sales_data)

# Regional tax rates
tax_data = {
    'region': ['North', 'South', 'East', 'West', 'Central'],
    'tax_rate': [0.05, 0.06, 0.07, 0.05, 0.06],
}

tax_df = pd.DataFrame(tax_data)

In [ ]:
# Merge sales and tax data using a right merge
merged_df = pd.merge(sales_df, tax_df, on='region', how='right')

display(merged_df)

region product   sales  tax_rate
0    North       A  1000.0      0.05
1    South       B  1200.0      0.06
2     East       C   900.0      0.07
3     West       D  1100.0      0.05
4  Central     NaN     NaN      0.06

#### Going Deeper

When we combine DataFrames, paying attention to certain details can help ensure that they are merged correctly. In the above, an important detail was that one DataFrame did not contain all the cities included in the other. In the example below, we notice some other important details to pay attention to.

In [ ]:
import pandas as pd

#Data not necessarily correct
iran_covid_data = {
    'Province': ['Tehran', 'Isfahan', 'Mazandaran', 'Khorasan Razavi', 'Fars', 'Gilan', 'Kerman', 'Khuzestan', 'Kermanshah', 'East Azerbaijan', 'Qom', 'Semnan', 'Golestan', 'West Azerbaijan', 'Markazi', 'Lorestan', 'Hormozgan', 'Yazd', 'Chaharmahal and Bakhtiari', 'Kohgiluyeh and Boyer-Ahmad', 'Ilam', 'Bushehr', 'North Khorasan', 'South Khorasan', 'Sistan and Baluchestan', 'Ardebil'],
    'Deaths': [22824, 5392, 5302, 4969, 4851, 3496, 3016, 2963, 2823, 2536, 2213, 2059, 2044, 2027, 2004, 1958, 1624, 1607, 1202, 996, 971, 961, 836, 778, 765, 762]
}

iran_covid_df = pd.DataFrame.from_dict(iran_covid_data)

In [ ]:


#Data not necessarily correct
gdp_data = {
    'province_name': ['Alborz', 'Ardabil', 'Bushehr', 'Chaharmahal and Bakhtiari', 'East Azerbaijan', 'Fars', 'Gilan', 'Golestan', 'Hamadan', 'Hormozgan', 'Ilam', 'Isfahan', 'Kerman', 'Kermanshah', 'Khuzestan', 'Kohgiluyeh and Boyer-Ahmad', 'Kurdistan', 'Lorestan', 'Markazi', 'Mazandaran', 'North Khorasan', 'Qazvin', 'Qom', 'Razavi Khorasan', 'Semnan', 'Sistan and Baluchestan', 'South Khorasan', 'Tehran', 'West Azerbaijan', 'Yazd', 'Zanjan'],
    'Abbreviation': ['AL', 'AR', 'BU', 'CB', 'EA', 'FA', 'GN', 'GO', 'HA', 'HO', 'IL', 'IS', 'KN', 'KE', 'KH', 'KB', 'KU', 'LO', 'MA', 'MN', 'NK', 'QA', 'QM', 'RK', 'SE', 'SB', 'SK', 'TE', 'WA', 'YA', 'ZA'],
    'Area (km2)': [5833, 17800, 22743, 16332, 45650, 122608, 14042, 20195, 19368, 70669, 20133, 107029, 183285, 24998, 64055, 15504, 29137, 28294, 29130, 23701, 28434, 15549, 11526, 118884, 97491, 180726, 151913, 18814, 37437, 76469, 21773],
    'GDP per capita': [12500, 9000, 10000, 6000, 7500, 7500, 7500, 6000, 6000, 8000, 6000, 7000, 9000, 8000, 6000, 6000, 6000, 8000, 6000, 8000, 6000, 7000, 7000, 6000, 7500, 6000, 5000, 6000, 8000, 8000, 8000],
    'Population (2023)': [2730000, 1284000, 1174000, 973000, 3925000, 4904000, 2546000, 1893000, 1756000, 1806000, 591000, 5136000, 3184000, 2003000, 4725000, 728000, 1614000, 1784000, 1436000, 3302000, 868000, 1284000, 1300000, 6444000, 715000, 2777000, 786000, 13323000, 3278000, 1156000, 1103000]
}

gdp_df = pd.DataFrame(gdp_data)
display(gdp_df)

province_name Abbreviation  Area (km2)  GDP per capita  \
0                       Alborz           AL        5833           12500   
1                      Ardabil           AR       17800            9000   
2                      Bushehr           BU       22743           10000   
3    Chaharmahal and Bakhtiari           CB       16332            6000   
4              East Azerbaijan           EA       45650            7500   
5                         Fars           FA      122608            7500   
6                        Gilan           GN       14042            7500   
7                     Golestan           GO       20195            6000   
8                      Hamadan           HA       19368            6000   
9                    Hormozgan           HO       70669            8000   
10                        Ilam           IL       20133            6000   
11                     Isfahan           IS      107029            7000   
12                      Kerman           KN      183285            9000   
13                  Kermanshah           KE       24998            8000   
14                   Khuzestan           KH       64055            6000   
15  Kohgiluyeh and Boyer-Ahmad           KB       15504            6000   
16                   Kurdistan           KU       29137            6000   
17                    Lorestan           LO       28294            8000   
18                     Markazi           MA       29130            6000   
19                  Mazandaran           MN       23701            8000   
20              North Khorasan           NK       28434            6000   
21                      Qazvin           QA       15549            7000   
22                         Qom           QM       11526            7000   
23             Razavi Khorasan           RK      118884            6000   
24                      Semnan           SE       97491            7500   
25      Sistan and Baluchestan           SB      180726            6000   
26              South Khorasan           SK      151913            5000   
27                      Tehran           TE       18814            6000   
28             West Azerbaijan           WA       37437            8000   
29                        Yazd           YA       76469            8000   
30                      Zanjan           ZA       21773            8000   

    Population (2023)  
0             2730000  
1             1284000  
2             1174000  
3              973000  
4             3925000  
5             4904000  
6             2546000  
7             1893000  
8             1756000  
9             1806000  
10             591000  
11            5136000  
12            3184000  
13            2003000  
14            4725000  
15             728000  
16            1614000  
17            1784000  
18            1436000  
19            3302000  
20             868000  
21            1284000  
22            1300000  
23            6444000  
24             715000  
25            2777000  
26             786000  
27           13323000  
28            3278000  
29            1156000  
30            1103000

In the above, we have two DataFrames, iran_covid_data and gdp_data. We want to merge the two DataFrames so that we can observe the relationship between GDP per capita and covid deaths per capita. To accomplish this, we first note the following:
*   To merge the two DataFrames, we can use the province name column in the two DataFrames. However, the province name column is different in each dataframe. To address this, we can use the left_on and right_on parameters to indicate which column refers to province in each DataFrame.
*   These data were assembled from a source of mediocre quality. Therefore we cannot be certain that the provinces in one DataFrame match the provinces in another. To address this issue, we can use an outer join, which enables us to see which provinces for which we lack a certain kind of data. An outer join is a good idea in this case because it allows you to keep all of the rows from both DataFrames, even if there is no match between the values in the specified column. An outer join combines the rows from both DataFrames and fills in missing values with NaN (Not a Number) or a specified fill value. This means that all the rows from both DataFrames are included in the resulting DataFrame, with NaN or the specified fill value used to represent missing data where there is no match in the specified column.




In [ ]:
outer_merged = pd.merge(iran_covid_df, gdp_df, left_on='Province', right_on = 'province_name', how='outer')
display(outer_merged)

Province   Deaths               province_name  \
0                       Tehran  22824.0                      Tehran   
1                      Isfahan   5392.0                     Isfahan   
2                   Mazandaran   5302.0                  Mazandaran   
3              Khorasan Razavi   4969.0                         NaN   
4                         Fars   4851.0                        Fars   
5                        Gilan   3496.0                       Gilan   
6                       Kerman   3016.0                      Kerman   
7                    Khuzestan   2963.0                   Khuzestan   
8                   Kermanshah   2823.0                  Kermanshah   
9              East Azerbaijan   2536.0             East Azerbaijan   
10                         Qom   2213.0                         Qom   
11                      Semnan   2059.0                      Semnan   
12                    Golestan   2044.0                    Golestan   
13             West Azerbaijan   2027.0             West Azerbaijan   
14                     Markazi   2004.0                     Markazi   
15                    Lorestan   1958.0                    Lorestan   
16                   Hormozgan   1624.0                   Hormozgan   
17                        Yazd   1607.0                        Yazd   
18   Chaharmahal and Bakhtiari   1202.0   Chaharmahal and Bakhtiari   
19  Kohgiluyeh and Boyer-Ahmad    996.0  Kohgiluyeh and Boyer-Ahmad   
20                        Ilam    971.0                        Ilam   
21                     Bushehr    961.0                     Bushehr   
22              North Khorasan    836.0              North Khorasan   
23              South Khorasan    778.0              South Khorasan   
24      Sistan and Baluchestan    765.0      Sistan and Baluchestan   
25                     Ardebil    762.0                         NaN   
26                         NaN      NaN                      Alborz   
27                         NaN      NaN                     Ardabil   
28                         NaN      NaN                     Hamadan   
29                         NaN      NaN                   Kurdistan   
30                         NaN      NaN                      Qazvin   
31                         NaN      NaN             Razavi Khorasan   
32                         NaN      NaN                      Zanjan   

   Abbreviation  Area (km2)  GDP per capita  Population (2023)  
0            TE     18814.0          6000.0         13323000.0  
1            IS    107029.0          7000.0          5136000.0  
2            MN     23701.0          8000.0          3302000.0  
3           NaN         NaN             NaN                NaN  
4            FA    122608.0          7500.0          4904000.0  
5            GN     14042.0          7500.0          2546000.0  
6            KN    183285.0          9000.0          3184000.0  
7            KH     64055.0          6000.0          4725000.0  
8            KE     24998.0          8000.0          2003000.0  
9            EA     45650.0          7500.0          3925000.0  
10           QM     11526.0          7000.0          1300000.0  
11           SE     97491.0          7500.0           715000.0  
12           GO     20195.0          6000.0          1893000.0  
13           WA     37437.0          8000.0          3278000.0  
14           MA     29130.0          6000.0          1436000.0  
15           LO     28294.0          8000.0          1784000.0  
16           HO     70669.0          8000.0          1806000.0  
17           YA     76469.0          8000.0          1156000.0  
18           CB     16332.0          6000.0           973000.0  
19           KB     15504.0          6000.0           728000.0  
20           IL     20133.0          6000.0           591000.0  
21           BU     22743.0         10000.0          1174000.0  
22           NK     28434.0          6000.0           868000.0  
23           SK    151913.0          5000.0    

We see that there are two provinces in the Province column of the left DataFrame, Khorasan Razavi and Ardebil, that did not match with something in the province_name in the right DataFrame, and seven provinces in the province_name column of the right DataFrame that did not match with a province in the Province column of the left.  However, we see that Ardabil appears in the right DataFrame—it did not match simply because it is spelled differently from the corresponding province in the left DataFrame (Ardebil).

To complete the analysis, we change the spelling of the Ardabil province in the left DataFrame so that it matches properly. Then, it will be necessary to decide what to do with rows for which there is missing data due to a province name in one DataFrame not matching with a province in the other. Some options are to remove those provinces from the analysis, find alternative data sources to provide the data, or guess appropriate values.

#### pd.merge overview

For reference, we outline the pd.merge function and how it works below. The description includes important parameters for the function that enable you to ensure that data is merged properly. It's not necessary to understand everything below immediately. For now, you can just skim over it to get a basic idea of how the function works. After, we will go through some examples to give you a better sense of how to think through merging tables.

pd.merge() is a function in the pandas library used for merging DataFrames in Python. It combines the data from two DataFrames based on a common column or index, allowing you to join and analyze data from different sources. The function has several parameters that control the merging behavior:



*   left: The first (left) DataFrame to be merged.
*   right: The second (right) DataFrame to be merged.
*   how: Determines the type of merge to be performed. Default is 'inner' The 'left', 'right', 'outer', and 'inner' options correspond to different types of merges: left outer join using keys from the left DataFrame, right outer join using keys from the right DataFrame, full outer join using keys from the union of both DataFrames, and inner join using keys from the intersection of both DataFrames, respectively.
*   on: The column (or list of columns) used to join the DataFrames. Both DataFrames must have the specified column(s). If not provided, the function will use the columns with the same names in both DataFrames.
*   left_on: The column(s) in the left DataFrame to use as the merge key(s). This can be used instead of, or in conjunction with, the on parameter.
*   right_on: The column(s) in the right DataFrame to use as the merge key(s). This can be used instead of, or in conjunction with, the on parameter.
*   left_index: If True, use the index from the left DataFrame as the merge key(s). The default is False.
*   right_index: If True, use the index from the right DataFrame as the merge key(s). The default is False.

#### Parting Notes
I hope you enjoyed this lesson on combining tables. This lesson has introduced the basic concepts of combining tables. With this basis of understanding, you will be able to effectively conquer similar tasks in the future.