## ۱.۴. ترکیب داده‌های جداول متفاوت


In [2]:
import pandas as pd

## مقدمه

اینجا نحوه کار با داده‌های برگرفته از چندین منبع را می‌آموزید. این کار به شما امکان می‌دهد تا قابلیت‌های داستان‌سرایی خود را افزایش دهید و یافته‌های ارزشمندی را به دست بیاورید. در این نوت‌بوک یاد می‌گیریم تا با استفاده از کتابخانه پانداس در پایتون داده‌های چندین جدول را با هم ادغام کنیم. 

## ادغام جداول متفاوت به چه معناست و چه مزایایی دارد؟ 

یادگیری نحوه ادغام جداول به چه دردی می‌خورد؟ برای شرح این موضوع، بیایید روی جدول زیر که در قالب دیتا‌فریم در پانداس تعریف شده، کار کنیم: 

In [3]:
# جدول مدنظر
product_data = {
    'Product ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Product Name': ['Laptop', 'Smartphone', 'Tablet', 'Smartwatch', 'Laptop', 'Smartphone', 'Tablet', 'Smartwatch'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics'],
    'Brand': ['Brand A', 'Brand A', 'Brand A', 'Brand A', 'Brand B', 'Brand B', 'Brand B', 'Brand B']
}

product_df = pd.DataFrame(product_data)
print("Product Table:")
display(product_df)

Product Table:


Product ID Product Name     Category    Brand
0         101       Laptop  Electronics  Brand A
1         102   Smartphone  Electronics  Brand A
2         103       Tablet  Electronics  Brand A
3         104   Smartwatch  Electronics  Brand A
4         105       Laptop  Electronics  Brand B
5         106   Smartphone  Electronics  Brand B
6         107       Tablet  Electronics  Brand B
7         108   Smartwatch  Electronics  Brand B

همان‌طور که در سمت چپ جدول می‌بینید، هر سطر حاوی یک شماره شاخص (۰، ۱، ۲، ۳ و ...) است. 
Product ID

اتریبیوت‌های این جدول نیز عبارتند از:

`Product ID`

`Product Name`

`Category`

`Brand`

اصطلاح «ترکیب جداول» به این معناست که ما اطلاعات موجود در یک جدول را با اطلاعات یک جدول دیگر ادغام می‌کنیم تا به مجموعه داده بزرگ‌تر و جامع‌تری دست پیدا کنیم. به عنوان مثال فرض کنید ما یک جدول دیگر هم داریم که حاوی اطلاعات زیر است: 

In [4]:
# جدولی جداگانه که حاوی اتریبیوت «پروداکت آی‌دی» (شناسه محصول) و «قیمت» است. 
cost_data = {
    'Product ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Cost': [800, 500, 300, 250, 850, 550, 350, 275]
}

cost_df = pd.DataFrame(cost_data)
print("\nCost Table:")
display(cost_df)


Cost Table:


Product ID  Cost
0         101   800
1         102   500
2         103   300
3         104   250
4         105   850
5         106   550
6         107   350
7         108   275

اگر جدول اول را به تنهایی مورد مطالعه قرار دهیم، اطلاعات چندانی به دست نخواهیم آورد. به عنوان مثال با کمک جدول اول به جز هیستوگرام انواع محصولات و این‌که هر «برند» یا نام تجاری چه محصولاتی ارائه می‌کند، چیز چندان بیشتری دستگیرمان نمی‌شود. اما ترکیب این جدول با جدول دوم اطلاعات بیشتری در اختیار ما قرار می‌دهد. مثلا میتوانیم:

- میانگین قیمت هر محصول را بدست بیاوریم. به عنوان مثال، میانگین قیمت تلفن هوشمند
- درصد تفاوت میانگین قیمت محصولات را دریابیم: مثلا درصد تفاوت میانگین قیمت تلفن هوشمند برند آ و برند ب 


## ادغام جداول در پانداس

نحوه ذخیره و ترکیب جداول، بسته به این‌که از چه زبان برنامه‌نویسی‌ای استفاده می‌کنید، متفاوت است. در این نوت‌بوک، نحوه ذخیره داده در پانداس دیتافریم را می‌آموزیم و از پانداس برای ادغام آن‌ها استفاده می‌کنیم.   

در پایین ما  تابع 

`pd.merge` ([pandas.merge docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge.html)) 

را برای ادغام دیتافریم پایین به کار می‌بریم::

In [5]:
pd.merge(product_df, cost_df, on='Product ID')

Product ID Product Name     Category    Brand  Cost
0         101       Laptop  Electronics  Brand A   800
1         102   Smartphone  Electronics  Brand A   500
2         103       Tablet  Electronics  Brand A   300
3         104   Smartwatch  Electronics  Brand A   250
4         105       Laptop  Electronics  Brand B   850
5         106   Smartphone  Electronics  Brand B   550
6         107       Tablet  Electronics  Brand B   350
7         108   Smartwatch  Electronics  Brand B   275

`pd.merge` 

همچنین حاوی پارامتر

`how`

است. در مثال بالا، از آن‌جایی که نحوه استفاده از این پارامتر را تعریف نکرده‌ایم، این تابع به صورت پیش‌فرض، «مقدار» 

`inner`

را مد نظر قرار داده است. کمی جلوتر، بیشتر درباره استفاده از پارامتر

`how`

صحبت می‌کنیم.

پیش از ادغام جداول، بهتر است به نوع جدول ادغام شده‌مان فکر کنیم و ببینیم به دنبال چه چیزی در جدول نهایی هستیم. این کار به شما کمک می‌کند تا عملگری را برای ادغام جداول به کار ببرید که پاسخگوی نیاز شماست. 

زمانی که می‌خواهیم جداول را با هم ادغام می‌کنیم، باید از یک ستون مشترک استفاده کنیم. در مثال بالا ما از ستون

Product ID 

برای این کار استفاده کردیم. توجه داشته باشید که هر دو جدول دارای «پروداکت آی‌دی» های یکسان است: نخستین آی‌دی ۱۰۱ و آخرین آن ۱۰۸ است. فرض کنید یکی از این جداول فقط شش «پروداکت آی‌دی» داشت (از ۱۰۱ تا ۱۰۶). آن زمان چه باید کرد؟ اینجاست که ما از پارامتر

'how'

استفاده می‌کنیم. در مثال‌های پایین نشان می‌دهیم که از طریق ادغام‌های مختلف می‌توان با مجموعه‌داده‌هایی در دیتافریم کار کرد که داده‌های آن ناقص است.

#### Left Merge (`how` = left)

فرض کنید ما مجموعه داده‌ای در اختیار داریم که حاوی تمام شهرهایی است که نوعی بیماری خاص در آن شیوع پیدا کرده است. این مجموعه داده حاوی نام این شهرها و شناسه منحصر به فرد هر شهر است. حال فرض کنید یک مجموعه داده دیگر هم داریم که حاوی  شناسه و جمعیت شهرها است، اما شناسه تمامی شهرهایی که بیماری در آن شیوع پیدا کرده، در این جدول دوم وجود ندارد. حال تصور کنید می‌خواهیم جدولی بسازیم از اسامی تمامی شهرها و جمعیتشان و می‌خواهیم تمامی شهرهایی که با شیوع بیماری مواجهند هم در این جدول موجود باشند. برای انجام این کار از روش زیر استفاده می‌کنیم: 

In [6]:
iranian_cities = pd.DataFrame({'city_id': [1, 2, 3], 'city_name': ['Tehran', 'Mashhad', 'Isfahan']})
city_populations = pd.DataFrame({'city_id': [1, 2], 'population': [9172195, 3203253]})

merged = pd.merge(left = iranian_cities, right = city_populations, on='city_id', how='left')
merged

city_id city_name  population
0        1    Tehran   9172195.0
1        2   Mashhad   3203253.0
2        3   Isfahan         NaN

عمل

`merge`

بر اساس ستون

`city_id`

تمامی سطرهای دیتافریم سمت چپ

(`iranian_cities`)

را با سطرهای مشابه دیتافریم سمت راست

(`city_populations`) 

مطابقت می‌دهد. اگر اطلاعات دیتافریم سمت چپ با سطری در دیتافریم سمت راست مطابقت پیدا کند، اطلاعات آن سطر در دیتافریم نهایی درج خواهد شد، اما اگر این اطلاعات موجود نباشد، عبارت

NaN

را در دیتافریم نهایی خواهیم دید.

#### Right Merge (`how` = right)


در این شرایط ما از

`how='left'`

استفاده می‌کنیم تا مطمئن شویم فارغ از مطابقعت اطلاعات دیتافریم

`iranian_cities`

با سطری در دیتافریم

`city_populations`

تمامی شهرهای دیتافریم

`iranian_cities`

در دیتافریم نهایی مندرج شود.  اگر از گزاره  

`how='right'`

استفاده می‌کردیم، تنها شهرهایی از ازدیتافریم

`city_populations`

در دیتافریم نهایی مندرج می‌شد که با سطری در دیتافریم

`iranian_cities`

مطابقت دارند.

In [7]:
right_merged = pd.merge(iranian_cities, city_populations, on='city_id', how='right')
right_merged

city_id city_name  population
0        1    Tehran     9172195
1        2   Mashhad     3203253

در مثال بالا ما از ادغام سمت چپ استفاده کردیم و آن را با دیتافریم سمت راست مطابقت دادیم. برای بررسی ادغام‌های دیگر، چند مثال دیگر می‌زنیم.

#### Inner Merge (`how` = inner)

فرض کنید می‌خواهیم جدولی بسازیم از محتوای غذایی میوه‌های مورد علاقه دوستانمان. جدولی داریم حاوی نام دوستان و میوه مورد علاقه‌شان و جدول دیگری که حاوی محتوای غذایی میوه‌ها. حال ببینیم ادغام درونی

inner merge

و بیرونی

outer merge

چیست و چه تفاوتی با هم دارند.

In [11]:
# جدول اول که حاوی نام افراد و میوه مورد علاقه آن‌هاست

people_fruits_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Edward"],
    "Favorite_Fruit": ["Apple", "Banana", "Grapes", "Orange","Papaya"]
}

people_fruits_df = pd.DataFrame(people_fruits_data)

# جدول دوم که حاوی میوه‌ها و محتوای غذایی آن‌هاست

nutritional_content_data = {
    "Fruit": ["Apple", "Banana", "Grapes", "Orange", "Pineapple"],
    "Calories": [95, 89, 67, 47, 50],
    "Vitamin_C_mg": [4.6, 8.7, 3.2, 45, 48],
    "Fiber_g": [2.4, 2.6, 0.9, 2.4, 1.4]
}

nutritional_content_df = pd.DataFrame(nutritional_content_data)

حال به روش ادغام درونی این دو جدول را با هم ترکیب می‌کنیم.

In [12]:
# ادغام به روش ادغام درونی

merged_data = pd.merge(
    people_fruits_df, nutritional_content_df,
    left_on="Favorite_Fruit", right_on="Fruit",
    how="inner"
)

# حذف ستون تکراری «میوه»

merged_data = merged_data.drop(columns="Fruit")

# نمایش جدول ادغام شده

display(merged_data)

Name Favorite_Fruit  Calories  Vitamin_C_mg  Fiber_g
0    Alice          Apple        95           4.6      2.4
1      Bob         Banana        89           8.7      2.6
2  Charlie         Grapes        67           3.2      0.9
3    David         Orange        47          45.0      2.4

#### Outer Merge (`how` = outer)

حال ببینید چه می‌شود وقتی ما از ادغام بیرونی استفاده می‌کنیم.


In [13]:
# ادغام به روش ادغام بیرونی

merged_data = pd.merge(
    people_fruits_df, nutritional_content_df,
    left_on="Favorite_Fruit", right_on="Fruit",
    how="outer"
)

# حذف ستون تکراری «میوه»

merged_data = merged_data.drop(columns="Fruit")

# نمایش جدول ادغام شده

display(merged_data)

Name Favorite_Fruit  Calories  Vitamin_C_mg  Fiber_g
0    Alice          Apple      95.0           4.6      2.4
1      Bob         Banana      89.0           8.7      2.6
2  Charlie         Grapes      67.0           3.2      0.9
3    David         Orange      47.0          45.0      2.4
4   Edward         Papaya       NaN           NaN      NaN
5      NaN            NaN      50.0          48.0      1.4

ادغام درونی

inner merge (or inner join)

بر اساس سطر‌های مشترک انتخاب شده دو مجموعه داده را با هم ادغام می‌کند و فقط اطلاعاتی را در جدول نهایی می‌آورد که با هم همخوانی دارند. 

ادغام بیرونی

outer merge (or outer join)

تمامی سطور هر دو مجموعه داده را در جدول نهایی مندرج می‌کند و برای بخش‌هایی که با هم منطبق نیستند از عبارت

NaN

استفاده می‌کند.

شما همچنین می‌توانید با استفاده از پارامتر

"how"

در ادغام بالا، این ادغام را به ادغام چپ و راست تغییر دهید و تفاوت آن با ادغام درونی و بیرونی را ببینید.

#### یافتن ادغام مناسب

ما می‌توانیم بر اساس تحلیلی که مدنظرمان است می‌توانیم نوع ادغاممان را مشخص کنیم. مثلا در مثال پایین می‌خواهیم محل زندگی مشتریان محصولات مختلف را تحلیل کنیم.

در این مورد، استفاده از ادغام راست منطقی است چرا که تمرکز اصلی روی تاریخ فروش محصول است و می‌خواهیم تمامی اطلاعات فروش در جدول نهایی موجود باشد. ادغام راست، تمامی اطلاعات فروش محصولات را فارغ از تطابق آن‌ها با خریداران در جدول نهایی منعکس می‌کند.  

اگر از ادغام چپ یا درونی استفاده می‌کردیم، محصولاتی را که با خریداری مطابقت نداشت، حذف می‌کرد و در جدول نهایی نمی‌آورد. این جدول احتمالا به کار ما نمی‌آید چرا که ما برای تحلیلمان به اطلاعات سایر محصولات نیز نیاز داریم.

In [16]:
# مجموعه داده حاوی اطلاعات خریداران
customer_information_data = {
    "ID": [1, 2, 3, 4],
    "Name": ["John Doe", "Jane Smith", "Michael Brown", "Lucy Green"],
    "Email": ["john.doe@example.com", "jane.smith@example.com", "michael.brown@example.com", "lucy.green@example.com"],
    "Location": ["New York, NY","New York, NY","Chester, NJ","Boston, MA"]
}

customer_information_df = pd.DataFrame(customer_information_data)

# مجموعه داده حاوی اطلاعات محصولات
product_sales_data = {
    "Product_ID": [101, 102, 103, 104, 105],
    "Product_Name": ["Laptop", "Monitor", "Keyboard", "Mouse", "Headset"],
    "Units_Sold": [50, 120, 200, 180, 80],
    "Customer_ID": [1, 2, 3, 1, 3]
}

product_sales_df = pd.DataFrame(product_sales_data)


In [15]:
# ادغام داده‌ها
merged_data = pd.merge(customer_information_df,
    product_sales_df,
    left_on="ID", right_on="Customer_ID",
    how="right"
)
display(merged_data)

ID           Name                      Email      Location  Product_ID  \
0   1       John Doe       john.doe@example.com  New York, NY         101   
1   2     Jane Smith     jane.smith@example.com  New York, NY         102   
2   3  Michael Brown  michael.brown@example.com   Chester, NJ         103   
3   1       John Doe       john.doe@example.com  New York, NY         104   
4   3  Michael Brown  michael.brown@example.com   Chester, NJ         105   

  Product_Name  Units_Sold  Customer_ID  
0       Laptop          50            1  
1      Monitor         120            2  
2     Keyboard         200            3  
3        Mouse         180            1  
4      Headset          80            3

در مثال پایین دو مجموعه داده کوچک داریم: یکی حاوی اطلاعات فروش محصولات مختلف در مناطق متفاوت است و دیگری حاوی میزان مالیات مناطق مختلف. در این‌جا ادغام راست به ما امکان می‌دهد تا فارغ از مطابقت اطلاعات مالیاتی با اطلاعات فروش، تمامی اطلاعات مالیاتی در جدول نهایی منعکس شود. 

In [ ]:
# داده فروش
sales_data = {
    'region': ['North', 'South', 'East', 'West'],
    'product': ['A', 'B', 'C', 'D'],
    'sales': [1000, 1200, 900, 1100],
}

sales_df = pd.DataFrame(sales_data)

# داده مالیات منطقه‌ای
tax_data = {
    'region': ['North', 'South', 'East', 'West', 'Central'],
    'tax_rate': [0.05, 0.06, 0.07, 0.05, 0.06],
}

tax_df = pd.DataFrame(tax_data)

In [ ]:
# ادغام دو مجموعه داده
merged_df = pd.merge(sales_df, tax_df, on='region', how='right')

display(merged_df)

region product   sales  tax_rate
0    North       A  1000.0      0.05
1    South       B  1200.0      0.06
2     East       C   900.0      0.07
3     West       D  1100.0      0.05
4  Central     NaN     NaN      0.06

#### نگاهی عمیق‌تر

هنگام ادغام دیتافریم‌ها، توجه به برخی جزئیات به ما کمک می‌کند تا از ادغام صحیح آن‌ها اطمینان حاصل کنیم. در مثال بالا، آن‌چه باید به آن توجه می‌شد این بود که اسامی تمامی شهرهای موجود در یک دیتافریم، در دیتافریم دیگر وجود ندارد. در مورد پایین نیز ما متوجه مورد دیگری می‌شویم که باید به آن توجه کنیم. 

In [20]:
import pandas as pd

#داده‌ای که لزوما درست نیست
iran_covid_data = {
    'Province': ['Tehran', 'Isfahan', 'Mazandaran', 'Khorasan Razavi', 'Fars', 'Gilan', 'Kerman', 'Khuzestan', 'Kermanshah', 'East Azerbaijan', 'Qom', 'Semnan', 'Golestan', 'West Azerbaijan', 'Markazi', 'Lorestan', 'Hormozgan', 'Yazd', 'Chaharmahal and Bakhtiari', 'Kohgiluyeh and Boyer-Ahmad', 'Ilam', 'Bushehr', 'North Khorasan', 'South Khorasan', 'Sistan and Baluchestan', 'Ardebil'],
    'Deaths': [22824, 5392, 5302, 4969, 4851, 3496, 3016, 2963, 2823, 2536, 2213, 2059, 2044, 2027, 2004, 1958, 1624, 1607, 1202, 996, 971, 961, 836, 778, 765, 762]
}

iran_covid_df = pd.DataFrame.from_dict(iran_covid_data)

In [21]:


#داده‌ای که لزوما درست نیست
gdp_data = {
    'province_name': ['Alborz', 'Ardabil', 'Bushehr', 'Chaharmahal and Bakhtiari', 'East Azerbaijan', 'Fars', 'Gilan', 'Golestan', 'Hamadan', 'Hormozgan', 'Ilam', 'Isfahan', 'Kerman', 'Kermanshah', 'Khuzestan', 'Kohgiluyeh and Boyer-Ahmad', 'Kurdistan', 'Lorestan', 'Markazi', 'Mazandaran', 'North Khorasan', 'Qazvin', 'Qom', 'Razavi Khorasan', 'Semnan', 'Sistan and Baluchestan', 'South Khorasan', 'Tehran', 'West Azerbaijan', 'Yazd', 'Zanjan'],
    'Abbreviation': ['AL', 'AR', 'BU', 'CB', 'EA', 'FA', 'GN', 'GO', 'HA', 'HO', 'IL', 'IS', 'KN', 'KE', 'KH', 'KB', 'KU', 'LO', 'MA', 'MN', 'NK', 'QA', 'QM', 'RK', 'SE', 'SB', 'SK', 'TE', 'WA', 'YA', 'ZA'],
    'Area (km2)': [5833, 17800, 22743, 16332, 45650, 122608, 14042, 20195, 19368, 70669, 20133, 107029, 183285, 24998, 64055, 15504, 29137, 28294, 29130, 23701, 28434, 15549, 11526, 118884, 97491, 180726, 151913, 18814, 37437, 76469, 21773],
    'GDP per capita': [12500, 9000, 10000, 6000, 7500, 7500, 7500, 6000, 6000, 8000, 6000, 7000, 9000, 8000, 6000, 6000, 6000, 8000, 6000, 8000, 6000, 7000, 7000, 6000, 7500, 6000, 5000, 6000, 8000, 8000, 8000],
    'Population (2023)': [2730000, 1284000, 1174000, 973000, 3925000, 4904000, 2546000, 1893000, 1756000, 1806000, 591000, 5136000, 3184000, 2003000, 4725000, 728000, 1614000, 1784000, 1436000, 3302000, 868000, 1284000, 1300000, 6444000, 715000, 2777000, 786000, 13323000, 3278000, 1156000, 1103000]
}

gdp_df = pd.DataFrame(gdp_data)
display(gdp_df)

province_name Abbreviation  Area (km2)  GDP per capita  \
0                       Alborz           AL        5833           12500   
1                      Ardabil           AR       17800            9000   
2                      Bushehr           BU       22743           10000   
3    Chaharmahal and Bakhtiari           CB       16332            6000   
4              East Azerbaijan           EA       45650            7500   
5                         Fars           FA      122608            7500   
6                        Gilan           GN       14042            7500   
7                     Golestan           GO       20195            6000   
8                      Hamadan           HA       19368            6000   
9                    Hormozgan           HO       70669            8000   
10                        Ilam           IL       20133            6000   
11                     Isfahan           IS      107029            7000   
12                      Kerman           KN      183285            9000   
13                  Kermanshah           KE       24998            8000   
14                   Khuzestan           KH       64055            6000   
15  Kohgiluyeh and Boyer-Ahmad           KB       15504            6000   
16                   Kurdistan           KU       29137            6000   
17                    Lorestan           LO       28294            8000   
18                     Markazi           MA       29130            6000   
19                  Mazandaran           MN       23701            8000   
20              North Khorasan           NK       28434            6000   
21                      Qazvin           QA       15549            7000   
22                         Qom           QM       11526            7000   
23             Razavi Khorasan           RK      118884            6000   
24                      Semnan           SE       97491            7500   
25      Sistan and Baluchestan           SB      180726            6000   
26              South Khorasan           SK      151913            5000   
27                      Tehran           TE       18814            6000   
28             West Azerbaijan           WA       37437            8000   
29                        Yazd           YA       76469            8000   
30                      Zanjan           ZA       21773            8000   

    Population (2023)  
0             2730000  
1             1284000  
2             1174000  
3              973000  
4             3925000  
5             4904000  
6             2546000  
7             1893000  
8             1756000  
9             1806000  
10             591000  
11            5136000  
12            3184000  
13            2003000  
14            4725000  
15             728000  
16            1614000  
17            1784000  
18            1436000  
19            3302000  
20             868000  
21            1284000  
22            1300000  
23            6444000  
24             715000  
25            2777000  
26             786000  
27           13323000  
28            3278000  
29            1156000  
30            1103000

در مثال بالا دو مجموعه داده داریم

iran_covid_data

و

gdp_data. 

می‌خواهیم از طریق ادغام داده‌ها رابطه سرانه تولید ناخالص داخلی با سرانه مرگ و میر ناشی از کرونا را بررسی کنیم. برای انجام این‌کار باید به این نکات توجه داشته باشیم:


۱.   برای ادغام این دو دیتافریم، می‌توانیم از ستون مشترک استان استفاده کنیم، اما نکته اینجاست که نام ستون استان در دو دیتافریم متفاوت است. برای حل این مشکل، می‌توانیم از پارامترهای


left_on 

و

right_on 

استفاده کنیم تا مشخص کنیم مقصودمان کدام ستون‌ها در این دو دیتافریم است.


۲.   این دو مجموعه داده دارای کیفیت چندانی نیستند و اطلاعات مربوط به استان‌ها کامل نیست. برای حل این مشکل می‌توانیم از ادغام بیرونی استفاده کنیم. ادغام بیرونی به ما این امکان را می‌دهد تا استان‌هایی را که با نقص داده مواجهند شناسایی کنیم. ادغام بیرونی برای این نوع مجموعه داده مناسب است، چرا که فارغ از مطابقت اطلاعات دو مجموعه داده، تمامی اطلاعات را در جدول نهایی مندرج می کند. اگر اطلاعات تکمیلی مرتبط با یک استان در یکی از دیتافریم‌ها موجود نباشد، در جدول نهایی با عبارت 

NaN

مواجه می‌شویم.

In [22]:
outer_merged = pd.merge(iran_covid_df, gdp_df, left_on='Province', right_on = 'province_name', how='outer')
display(outer_merged)

Province   Deaths               province_name  \
0                       Tehran  22824.0                      Tehran   
1                      Isfahan   5392.0                     Isfahan   
2                   Mazandaran   5302.0                  Mazandaran   
3              Khorasan Razavi   4969.0                         NaN   
4                         Fars   4851.0                        Fars   
5                        Gilan   3496.0                       Gilan   
6                       Kerman   3016.0                      Kerman   
7                    Khuzestan   2963.0                   Khuzestan   
8                   Kermanshah   2823.0                  Kermanshah   
9              East Azerbaijan   2536.0             East Azerbaijan   
10                         Qom   2213.0                         Qom   
11                      Semnan   2059.0                      Semnan   
12                    Golestan   2044.0                    Golestan   
13             West Azerbaijan   2027.0             West Azerbaijan   
14                     Markazi   2004.0                     Markazi   
15                    Lorestan   1958.0                    Lorestan   
16                   Hormozgan   1624.0                   Hormozgan   
17                        Yazd   1607.0                        Yazd   
18   Chaharmahal and Bakhtiari   1202.0   Chaharmahal and Bakhtiari   
19  Kohgiluyeh and Boyer-Ahmad    996.0  Kohgiluyeh and Boyer-Ahmad   
20                        Ilam    971.0                        Ilam   
21                     Bushehr    961.0                     Bushehr   
22              North Khorasan    836.0              North Khorasan   
23              South Khorasan    778.0              South Khorasan   
24      Sistan and Baluchestan    765.0      Sistan and Baluchestan   
25                     Ardebil    762.0                         NaN   
26                         NaN      NaN                      Alborz   
27                         NaN      NaN                     Ardabil   
28                         NaN      NaN                     Hamadan   
29                         NaN      NaN                   Kurdistan   
30                         NaN      NaN                      Qazvin   
31                         NaN      NaN             Razavi Khorasan   
32                         NaN      NaN                      Zanjan   

   Abbreviation  Area (km2)  GDP per capita  Population (2023)  
0            TE     18814.0          6000.0         13323000.0  
1            IS    107029.0          7000.0          5136000.0  
2            MN     23701.0          8000.0          3302000.0  
3           NaN         NaN             NaN                NaN  
4            FA    122608.0          7500.0          4904000.0  
5            GN     14042.0          7500.0          2546000.0  
6            KN    183285.0          9000.0          3184000.0  
7            KH     64055.0          6000.0          4725000.0  
8            KE     24998.0          8000.0          2003000.0  
9            EA     45650.0          7500.0          3925000.0  
10           QM     11526.0          7000.0          1300000.0  
11           SE     97491.0          7500.0           715000.0  
12           GO     20195.0          6000.0          1893000.0  
13           WA     37437.0          8000.0          3278000.0  
14           MA     29130.0          6000.0          1436000.0  
15           LO     28294.0          8000.0          1784000.0  
16           HO     70669.0          8000.0          1806000.0  
17           YA     76469.0          8000.0          1156000.0  
18           CB     16332.0          6000.0           973000.0  
19           KB     15504.0          6000.0           728000.0  
20           IL     20133.0          6000.0           591000.0  
21           BU     22743.0         10000.0          1174000.0  
22           NK     28434.0          6000.0           868000.0  
23           SK    151913.0          5000.0    

در جدول نهایی می‌بینیم که در خصوص دو استان موجود در ستون

Province

دیتافریم سمت چپ (خراسان رضوی و اردبیل)، اطلاعاتی در ستون 

province_name 

دیتافریم سمت راست موجود نیست. همچنین می‌بینیم که نام هفت استان موجود در ستون  

province_name

دیتافریم سمت راست، در ستون  

Province

دیتافریم سمت چپ نیامده است. در خصوص اردبیل، نکته این‌جاست که نحوه نوشتار این استان در دو دیتافریم با هم متفاوت است.

برای تکمیل تحلیلمان، ما نحوه نوشتار استان‌ها را با هم منطبق می‌کنیم. سپس باید در خصوص اطلاعات ناقص باید تصمیمگیری کنیم. گاه می‌توانیم این اطلاعات را از جدول نهایی حذف کرد و به حساب نیاورد و گاه باید برای پیدا کردن اطلاعات ناقص به دنبال یک مجموعه داده سوم بود.

#### pd.merge نگاهی به

در اینجا بار دیگر به تابع

pd.merge


نگاهی اجمالی خواهیم داشت. توضیحاتی که در این‌جا می‌آید حاوی پارامترهای مهمی است که به شما کمک می‌کند داده‌هایتان را به درستی ادغام کنید. فعلا نیازی نیست که جزئیات این ادغام را کاملا درک کنید. می‌توانید نگاهی سریع به آن بیاندازید تا نحوه عملکرد این ادغام تا حدی دستتان بیاید. بعدتر مثال‌هایی در این خصوص خواهیم زد. 

pd.merge() 

تابعی در کتابخانه پانداس است که برای ادغام دیتافریم‌ها در پایتون مورد استفاده قرار می‌گیرد. این تابع با کمک ستون یا نمایه مشترک، دیتافریم‌ها را با هم ادغام می‌کند و به شما این امکان را می‌دهد تا داده‌ها را با هم ترکیب و سپس اطلاعات نهایی را تحلیل کنید. این تابع حاوی چندین پارامتر است که نوع و نحوه ادغام را تعیین می‌کند:

۱.  left

دیتافریم اول یا سمت چپ را به عنوان دیتافریم اصلی در نظر می‌گیرد.


۲.  right

دیتافریم اول یا سمت چپ را به عنوان دیتافریم اصلی در نظر می‌گیرد.


۳.  how

نحوه ادغام را تعیین می‌کند. مثلا ادغام درونی، بیرونی و گزینه‌های چپ یا راست. ادغام چپ بیرونی، کلیدها یا همان

keys

دیتافریم سمت چپ را مرجع قرار می‌دهد و ادغام راست بیرونی برعکس. 

ادغام بیرونی تنها، کلیدهای هر دو دیتافریم را مرجع قرار می‌دهد و ادغام درونی تنها، کلیدهای مشترک را. 


۴.  on

از پارامتر «آن» برای ادغام جداول بر اساس ستن‌ها استفاده می‌شود. برای استفاده از این پارامتر باید مطمئن باشیم که عنوان ستون‌ مدنظر در تمامی جداول یکی است.


۵. left_on

این پارامتر برای ادغام ستون‌های مشترک، ستون دیتافریم سمت چپ را مرجع قرار می‌دهد.


۶. right_on

این پارامتر برای ادغام ستون‌های مشترک، ستون دیتافریم سمت راست را مرجع قرار می‌دهد.


۷.  left_index

این پارامتر، فهرست یا نمایه دیتافریم سمت چپ را مرجع قرار می‌دهد.


۸. right_index 

این پارامتر، فهرست یا نمایه دیتافریم سمت چپ را مرجع قرار می‌دهد.

#### سخن آخر

امیدوارم از آموزه‌های این نوت‌بوک لذت برده باشید. این نوت‌بوک نگاهی مقدماتی داشت به ایده ترکیب جداول. حال شما می‌توانید روش‌های بررسی شده در این نوت‌بوک را برای تحلیل داده‌های خود به کار ببرید.